// Room components barrel export
export { default as Room } from './Room'
export { default as Walls } from './Walls'
export { default as Floor } from './Floor'
export { default as Window } from './Window'
export { default as DeskSetup } from './DeskSetup'
export { default as Chair } from './Chair'
export { default as Cabinet } from './Cabinet'
export { default as Shelf } from './Shelf'
export { default as Clock } from './Clock'
export { default as TVSetup } from './TVSetup'
export { default as TVScreen } from './TVScreen'
export { default as Bed } from './Bed'
export { default as Plant } from './Plant'
export { default as Cat } from './Cat'
export { default as PlanBoard } from './PlanBoard'
export { default as InteractiveObject } from './InteractiveObject'
export { default as CameraController } from './CameraController'
export { COLORS } from './colors'
