-- ==============================================================================
-- SUPABASE SCHEMA FOR 3D PIXEL ROOM PORTFOLIO
-- Execute this SQL in the Supabase SQL Editor (https://supabase.com/dashboard)
-- ==============================================================================

-- 1. Create Profile Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL DEFAULT 'Le Trong Nghia',
  title_vi TEXT NOT NULL DEFAULT 'Sinh viên CNTT tại HUFLIT',
  title_en TEXT NOT NULL DEFAULT 'IT Student at HUFLIT',
  tagline_vi TEXT DEFAULT 'Full-stack Developer • Three.js • React • Node.js',
  tagline_en TEXT DEFAULT 'Full-stack Developer • Three.js • React • Node.js',
  intro_vi TEXT DEFAULT 'Xin chào! Mình là Nghĩa - sinh viên IT tại HUFLIT với đam mê phát triển web.',
  intro_en TEXT DEFAULT 'Hello! I am Nghia - an IT student at HUFLIT passionate about web development.',
  description_vi TEXT,
  description_en TEXT,
  email TEXT DEFAULT 'ltn66441@gmail.com',
  phone TEXT DEFAULT '(+84) 0778706084',
  github TEXT DEFAULT 'https://github.com/YouAreMyHome',
  linkedin TEXT DEFAULT 'https://www.linkedin.com/in/youaremyhome/',
  website TEXT DEFAULT 'https://letrongnghia.me',
  location_vi TEXT DEFAULT 'TP. Hồ Chí Minh, Việt Nam 🇻🇳',
  location_en TEXT DEFAULT 'Ho Chi Minh City, Vietnam 🇻🇳',
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  description_en TEXT,
  full_description TEXT,
  full_description_en TEXT,
  image TEXT,
  tags TEXT[] DEFAULT '{}',
  features TEXT[] DEFAULT '{}',
  features_en TEXT[] DEFAULT '{}',
  role TEXT DEFAULT 'Full-stack Developer',
  team TEXT DEFAULT '1 thành viên',
  team_en TEXT DEFAULT '1 member',
  duration TEXT,
  duration_en TEXT,
  github TEXT,
  demo TEXT,
  featured BOOLEAN DEFAULT false,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Skills Table
CREATE TABLE IF NOT EXISTS public.skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL CHECK (category IN ('frontend', 'backend', 'tools')),
  name TEXT NOT NULL,
  level INT NOT NULL CHECK (level >= 0 AND level <= 100),
  icon TEXT,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Experiences Table
CREATE TABLE IF NOT EXISTS public.experiences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company TEXT NOT NULL,
  position TEXT NOT NULL,
  position_en TEXT,
  duration TEXT NOT NULL,
  duration_en TEXT,
  description TEXT,
  description_en TEXT,
  highlights TEXT[] DEFAULT '{}',
  highlights_en TEXT[] DEFAULT '{}',
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Create Playlist Table
CREATE TABLE IF NOT EXISTS public.playlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  artist TEXT NOT NULL,
  src TEXT NOT NULL,
  duration TEXT NOT NULL DEFAULT '3:30',
  cover_url TEXT,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Create Guestbook / Sticky Notes Table
CREATE TABLE IF NOT EXISTS public.guestbook (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_name TEXT NOT NULL,
  message TEXT NOT NULL,
  color TEXT DEFAULT '#fef08a', -- yellow sticky note
  pin_x NUMERIC(5,2) DEFAULT 0,
  pin_y NUMERIC(5,2) DEFAULT 0,
  is_approved BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Create Game High Scores Table
CREATE TABLE IF NOT EXISTS public.game_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_name TEXT NOT NULL CHECK (game_name IN ('snake', 'pong', 'dino', 'tetris')),
  player_name TEXT NOT NULL,
  score INT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Create Site Settings Table
CREATE TABLE IF NOT EXISTS public.site_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experiences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.playlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guestbook ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- Read policies (Public)
CREATE POLICY "Allow public read on profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Allow public read on projects" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Allow public read on skills" ON public.skills FOR SELECT USING (true);
CREATE POLICY "Allow public read on experiences" ON public.experiences FOR SELECT USING (true);
CREATE POLICY "Allow public read on playlist" ON public.playlist FOR SELECT USING (true);
CREATE POLICY "Allow public read on guestbook" ON public.guestbook FOR SELECT USING (is_approved = true);
CREATE POLICY "Allow public read on game_scores" ON public.game_scores FOR SELECT USING (true);
CREATE POLICY "Allow public read on site_settings" ON public.site_settings FOR SELECT USING (true);

-- Public insert for Guestbook and Game Scores
CREATE POLICY "Allow public insert to guestbook" ON public.guestbook FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert to game_scores" ON public.game_scores FOR INSERT WITH CHECK (true);

-- Admin full access policies (Authenticated users)
CREATE POLICY "Allow full access to authenticated on profiles" ON public.profiles FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access to authenticated on projects" ON public.projects FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access to authenticated on skills" ON public.skills FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access to authenticated on experiences" ON public.experiences FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access to authenticated on playlist" ON public.playlist FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access to authenticated on guestbook" ON public.guestbook FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access to authenticated on game_scores" ON public.game_scores FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access to authenticated on site_settings" ON public.site_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);
